// <auto-generated />
namespace Hunter.DataAccess.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addRoleMappingTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addRoleMappingTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201512250959541_addRoleMappingTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
